### ISSUE TITLE
Sabre\DAV\Exception\ServiceUnavailable: Storage is temporarily not available

### ISSUE THREAD

**Issue by Tony36051** [NastuzziSamy/files_external_gdrive#5] opened 2018-05-20 08:32 UTC
os: ubuntu 16.04
nextcloud version: 13.0.2
files_external_gdrive: 0.2.6

I did follow 3-step-installation:
1. First, clone the repo git clone https://github.com/NastuzziSamy/files_external_gdrive.git
2. Execute make install in the app directory
3. And enable the app with php occ app:enable files_external_gdrive in the Nextcloud directory

After I config OAuth2(clien ID, client secret)，when i click Files->GoogleDrive, a tip shown at the top "Storage is temporarily not available" . I have check the log that says:
```
Sabre\DAV\Exception\ServiceUnavailable: Storage is temporarily not available
/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 967: OCA\DAV\Connector\Sabre\ObjectTree->getNodeForPath('GoogleDrive')
/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1666: Sabre\DAV\Server->getPropertiesIteratorForPath('GoogleDrive', Array, 1)
/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 355: Sabre\DAV\Server->generateMultiStatus(Object(Generator), false)
[internal function] Sabre\DAV\CorePlugin->httpPropFind(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method PROPFIND', Array)
/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/var/www/nextcloud/apps/dav/appinfo/v1/webdav.php - line 80: Sabre\DAV\Server->exec()
/var/www/nextcloud/remote.php - line 164: require_once('/var/www/nextcl...')
{main}
```

I really need this app, and have been waiting for update from nextcloud for a long time. 
I can give more info if you need, thx

**Comment by NastuzziSamy** [comment] 2018-05-20 10:57
Hi @Tony36051, it's been two days i am working on it, i dont really know from where this issue came...

I will try to close this issue for monday, but still...

**Comment by Tony36051** [comment] 2018-05-22 13:47
If you can't reproduce it, I can email my vps' account to you. There is nothing but NC on it.
If nobody have this problem, I may doubt my setting about my google drive

**Comment by cyberfuzzie** [comment] 2018-05-23 00:09
No, it's not just you, I have the same problem.

    Sabre\DAV\Exception\ServiceUnavailable: Storage is temporarily not available
    /opt/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 967: OCA\DAV\Connector\Sabre\ObjectTree->getNodeForPath('GoogleDrive')
    /opt/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1666: Sabre\DAV\Server->getPropertiesIteratorForPath('GoogleDrive', Array, 1)
    /opt/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 355: Sabre\DAV\Server->generateMultiStatus(Object(Generator), false)
    [internal function] Sabre\DAV\CorePlugin->httpPropFind(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /opt/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /opt/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method PROPFIND', Array)
    /opt/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /opt/nextcloud/apps/dav/appinfo/v1/webdav.php - line 80: Sabre\DAV\Server->exec()
    /opt/nextcloud/remote.php - line 164: require_once('/opt/nextcloud/...')
    {main}

Nextcloud 13.0.2
files_external_gdrive 0.2.5
Apache 2.4.29
PHP 7.2.5

**Comment by NastuzziSamy** [comment] 2018-05-24 22:48
Finnaly, I found out the issue...
It was only caused by few commits before.

Sorry for the time I took to close this issue. 
I hope you will enjoy using files_external_gdrive @Tony36051 @cyberfuzzie

**Closed as completed by NastuzziSamy** 2018-05-24 22:48 UTC
Labels: bug, help wanted

**Comment by XerraX** [comment] 2018-05-25 19:00
Just updated to 0.2.6 and still got this issue.

**Comment by fa-ribeiro** [comment] 2018-05-25 19:32
Issue still present on 0.2.6

from the log files: 

> Declaration of OCA\Files_external_gdrive\Storage\Flysystem::buildFlySystem($adapter) should be compatible with OC\Files\Storage\Flysystem::buildFlySystem(League\Flysystem\AdapterInterface $adapter) at /var/www/nextcloud/apps/files_external_gdrive/lib/Storage/Flysystem.php#28

**Comment by NastuzziSamy** [comment] 2018-05-25 21:27
@XerraX @fa-ribeiro I think it depends on the php version.

It is know fixed, I think it is the only error, sorry guys
